-- tutto in italiano!!
-- 1.               creazione tabelle per gestionale

-- 1.1              gestione magazzino
-- 1.1.1            K_FILATI (ID, K_MATERIALE_ID, LUNGHEZZA, PESO, TENSIONE_ID, COLORE, PRODUTTORE, NOME_MODELLO, DATA_ACQUISTO, INTERO
CREATE TABLE K_TIPO_MATERIALE (
    MATERIALE_ID    NUMBER(10, 0),
    MATERIALE_NOME  VARCHAR2(100 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_TIPO_MATERIALE
    ADD CONSTRAINT PK_TIPO_MATERIAL
    PRIMARY KEY (MATERIALE_ID)
/
CREATE TABLE K_TENSIONI (
    TENSIONE_ID NUMBER(10, 0),
    TENSIONE_SCHEMA VARCHAR2(200 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_TENSIONI
    ADD CONSTRAINT PK_TENSIONI
    PRIMARY KEY (TENSIONE_ID)
/
CREATE TABLE K_TIPO_STRUMENTO (
    TIPO_ID     NUMBER(10, 0),
    TIPO_NOME   VARCHAR2(100 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_TIPO_STRUMENTO
    ADD CONSTRAINT PK_TIPO_STRUMENTO
    PRIMARY KEY (TIPO_ID)
/
INSERT INTO K_TIPO_STRUMENTO VALUES(1, 'UNCINETTO', SYSDATE)
/
INSERT INTO K_TIPO_STRUMENTO VALUES(2, 'FERRI', SYSDATE)
/
INSERT INTO K_TIPO_STRUMENTO VALUES(3, 'FERRI CIRCOLARI', SYSDATE)
/
INSERT INTO K_TIPO_STRUMENTO VALUES(4, 'UNCINETTO TUNISINO', SYSDATE)
/
CREATE TABLE K_STRUMENTI_CONSIGLIATI (
    CONSIGLI_ID NUMBER(10, 0),
    K_TIPO_STRUMENTI_ID       NUMBER(10, 0),
    CONSIGLI_MISURA NUMBER(10, 0),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
CREATE SEQUENCE SK_STRUMENTI_CONSIGLIATI
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_STRUMENTI_CONSIGLIATI
    ADD CONSTRAINT PK_STRUMENTI_CONSIGLIATI
    PRIMARY KEY (CONSIGLI_ID)
/
ALTER TABLE K_STRUMENTI_CONSIGLIATI
    ADD CONSTRAINT FK_TIPO_STRUMENTI_ID
        FOREIGN KEY (K_TIPO_STRUMENTI_ID)
        REFERENCES K_TIPO_STRUMENTO (TIPO_ID)
/
CREATE TABLE K_FILATI (
    FILATI_ID       NUMBER(10, 0),
    K_MATERIALE_ID  NUMBER(10, 0),
    FILATI_LUNGHEZZA    NUMBER(10, 0),
    FILATI_PESO         NUMBER(10, 0),
    FILATI_PROG         NUMBER(10, 0),
    K_TENSIONE_ID       NUMBER(10, 0),
    K_CONSIGLI_ID       NUMBER(10, 0),
    FILATI_COLORE       VARCHAR2(200 CHAR),
    FILATI_PRODUTTORE   VARCHAR2(200 CHAR),
    FILATI_MODELLO      VARCHAR2(200 CHAR),
    FILATI_DT_ACQUISTO  DATE,
    FILATI_INTERO       CHAR (1 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
CREATE SEQUENCE SK_FILATI
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_FILATI
    ADD CONSTRAINT PK_FILATI
    PRIMARY KEY (FILATI_ID)
/
ALTER TABLE K_FILATI
    ADD CONSTRAINT FK_MATERIALE_ID
        FOREIGN KEY (K_MATERIALE_ID)
        REFERENCES K_TIPO_MATERIALE (MATERIALE_ID)
/
ALTER TABLE K_FILATI
    ADD CONSTRAINT FK_TENSIONE_ID
        FOREIGN KEY (K_TENSIONE_ID)
        REFERENCES K_TENSIONI (TENSIONE_ID)
/
ALTER TABLE K_FILATI
    ADD CONSTRAINT FK_CONSIGLI_ID
        FOREIGN KEY (K_CONSIGLI_ID)
        REFERENCES K_STRUMENTI_CONSIGLIATI (CONSIGLI_ID)
/
COMMENT ON COLUMN K_FILATI.FILATI_PROG IS 'PROGRESSIVO AD INDICARE IL NUMERO DEL SET DI GOMITOLI PRESO'
/
CREATE TABLE K_STRUMENTI (
    STRUMENTO_ID        NUMBER(10, 0),
    K_TIPO_ID           NUMBER(10, 0),
    STRUMENTO_MISURA    NUMBER(10, 0),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
CREATE SEQUENCE SK_STRUMENTI
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_STRUMENTI
    ADD CONSTRAINT PK_STRUMENTI
    PRIMARY KEY (STRUMENTO_ID)
/
ALTER TABLE K_STRUMENTI
    ADD CONSTRAINT FK_TIPO_STRUMENTO_ID
    FOREIGN KEY (K_TIPO_ID)
    REFERENCES K_TIPO_STRUMENTO (TIPO_ID)
/
CREATE TABLE K_TIPO_LAVORI (
    TIPO_ID NUMBER(10, 0),
    TIPO_NOME  VARCHAR2(200 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_TIPO_LAVORI
    ADD CONSTRAINT PK_TIPO_LAVORI
    PRIMARY KEY (TIPO_ID)
/
INSERT INTO K_TIPO_LAVORI VALUES(1, 'CAPPELLO', SYSDATE)
/
INSERT INTO K_TIPO_LAVORI VALUES(2, 'SCIARPA', SYSDATE)
/
INSERT INTO K_TIPO_LAVORI VALUES(3, 'MAGLIONE', SYSDATE)
/

-- TODO.. ORA NON SERVE IMPLEMENTARLA
CREATE TABLE K_MODELLO (
    MODELLO_ID  NUMBER(10, 0),
    MODELLO_NOME    VARCHAR2(100 CHAR)
)
/
CREATE SEQUENCE SK_MODELLO
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_MODELLO
    ADD CONSTRAINT PK_MODELLO
    PRIMARY KEY (MODELLO_ID)
/
CREATE TABLE K_LAVORI (
    LAVORO_ID   NUMBER(10, 0),
    LAVORO_NOME NUMBER(10, 0),
    K_MODELLO_ID    NUMBER(10, 0),
    K_TIPO_LAVORO_ID    NUMBER(10, 0)
)
/
CREATE SEQUENCE SK_LAVORI
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_LAVORI
    ADD CONSTRAINT PK_LAVORI
    PRIMARY KEY (LAVORO_ID)
/
ALTER TABLE K_LAVORI
    ADD CONSTRAINT FK_MODELLO_ID
    FOREIGN KEY (K_MODELLO_ID)
    REFERENCES K_MODELLO (MODELLO_ID)
/
ALTER TABLE K_LAVORI
    ADD CONSTRAINT FK_TIPO_LAVORO
    FOREIGN KEY (K_TIPO_LAVORO_ID)
    REFERENCES K_TIPO_LAVORI (TIPO_ID)
/
CREATE TABLE K_R_MAGAZZINO_LAVORO (
    LAVORO_ID   NUMBER(10, 0),
    FILATI_ID   NUMBER(10, 0),
    STRUMENTI_ID    NUMBER(10, 0),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_R_MAGAZZINO_LAVORO
    ADD CONSTRAINT FK_LAVORO_ID
    FOREIGN KEY (LAVORO_ID)
    REFERENCES K_LAVORI (LAVORO_ID)
/
ALTER TABLE K_R_MAGAZZINO_LAVORO
    ADD CONSTRAINT FK_FILATI_ID
    FOREIGN KEY (FILATI_ID)
    REFERENCES K_FILATI (FILATI_ID)
/
ALTER TABLE K_R_MAGAZZINO_LAVORO
    ADD CONSTRAINT FK_STRUMENTI_ID
    FOREIGN KEY (STRUMENTI_ID)
    REFERENCES K_STRUMENTI (STRUMENTO_ID)
/

CREATE TABLE K_JACQUARD_SCHEMA (
    JACQUARD_ID     NUMBER(10, 0),
    JACQUARD_ROW    NUMBER(10, 0),
    JACQUARD_STRING VARCHAR2(200 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
CREATE SEQUENCE SK_JACQUARD_SCHEMA
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_JACQUARD_SCHEMA
    ADD CONSTRAINT PK_JACQUARD_SCHEMA
    PRIMARY KEY (JACQUARD_ID)
/
CREATE TABLE K_JACQUARD_COLOR (
    COLOR_CODE  CHAR(1 CHAR),
    COLOR_RGB VARCHAR2(8 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_JACQUARD_COLOR
    ADD CONSTRAINT PK_JACQUARD_COLOR
    PRIMARY KEY (COLOR_CODE)
/
CREATE TABLE K_R_LAVORO_JACQUARD (
    LAVORO_ID   NUMBER(10, 0),
    JACQUARD_ID NUMBER(10, 0),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_R_LAVORO_JACQUARD
    ADD CONSTRAINT FK_JACQUARD_LAVORO_ID
    FOREIGN KEY (LAVORO_ID)
    REFERENCES K_LAVORI (LAVORO_ID)
/
ALTER TABLE K_R_LAVORO_JACQUARD
    ADD CONSTRAINT FK_JACQUARD_ID
    FOREIGN KEY  (JACQUARD_ID)
    REFERENCES K_JACQUARD_SCHEMA (JACQUARD_ID)
/
CREATE TABLE K_ANAGRAFICA_CLIENTE (
    CLIENTE_ID  NUMBER(10, 0),
    CLIENTE_NOME    VARCHAR2 (200 CHAR),
    CLIENTE_COGNOME VARCHAR2 (200 CHAR),
    DT_LAST_MOD     TIMESTAMP(6)
)
/
CREATE SEQUENCE SK_ANAGRAFICA_CLIENTE
    START WITH 1
    INCREMENT BY 1
/
ALTER TABLE K_ANAGRAFICA_CLIENTE
    ADD CONSTRAINT PK_ANAGRAFICA_CLIENTE
    PRIMARY KEY (CLIENTE_ID)
/
CREATE TABLE K_R_CLIENTE_LAVORO (
    CLIENTE_ID  NUMBER(10, 0),
    LAVORO_ID   NUMBER(10, 0),
    CLIENTE_LAVORO_DT_SCADENZA DATE,
    DT_LAST_MOD     TIMESTAMP(6)
)
/
ALTER TABLE K_R_CLIENTE_LAVORO
    ADD CONSTRAINT FK_CLIENTE_ID
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES K_ANAGRAFICA_CLIENTE (CLIENTE_ID)
/
ALTER TABLE K_R_CLIENTE_LAVORO
    ADD CONSTRAINT FK_CLIENTE_LAVORO_ID
    FOREIGN KEY (LAVORO_ID)
    REFERENCES K_LAVORI (LAVORO_ID)
/
COMMIT
/